LOCAL_PATH := $(call my-dir)

ifeq ($(BOARD_OMX_WITH_TVP),true)
    lib_dir := tvp/
else
    lib_dir :=
endif

include $(CLEAR_VARS)
LOCAL_MODULE := libstagefrighthw
LOCAL_SRC_FILES := libstagefrighthw
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := $(lib_dir)$(LOCAL_MODULE)$(LOCAL_MODULE_SUFFIX)
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(TARGET_OUT)/lib/
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libthreadworker_alt
LOCAL_SRC_FILES := libthreadworker_alt
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := $(lib_dir)$(LOCAL_MODULE)$(LOCAL_MODULE_SUFFIX)
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(TARGET_OUT)/lib/
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libOmxVideo
LOCAL_SRC_FILES := libOmxVideo
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := $(lib_dir)$(LOCAL_MODULE)$(LOCAL_MODULE_SUFFIX)
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(TARGET_OUT)/lib/
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libOmxCore
LOCAL_SRC_FILES := libOmxCore
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := $(lib_dir)$(LOCAL_MODULE)$(LOCAL_MODULE_SUFFIX)
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(TARGET_OUT)/lib/
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libOmxClock
LOCAL_SRC_FILES := libOmxClock 
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := $(lib_dir)$(LOCAL_MODULE)$(LOCAL_MODULE_SUFFIX)
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(TARGET_OUT)/lib/
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libOmxBase
LOCAL_SRC_FILES := libOmxBase
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := $(lib_dir)$(LOCAL_MODULE)$(LOCAL_MODULE_SUFFIX)
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(TARGET_OUT)/lib/
include $(BUILD_PREBUILT)


include $(CLEAR_VARS)
LOCAL_MODULE := libOmxAudio
LOCAL_SRC_FILES := libOmxAudio
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := $(lib_dir)$(LOCAL_MODULE)$(LOCAL_MODULE_SUFFIX)
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(TARGET_OUT)/lib/
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libomx_worker_peer_alt
LOCAL_SRC_FILES := libomx_worker_peer_alt
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := $(lib_dir)$(LOCAL_MODULE)$(LOCAL_MODULE_SUFFIX)
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(TARGET_OUT)/lib/
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libomx_timed_task_queue_alt
LOCAL_SRC_FILES := libomx_timed_task_queue_alt
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := $(lib_dir)$(LOCAL_MODULE)$(LOCAL_MODULE_SUFFIX)
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(TARGET_OUT)/lib/
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libomx_framework_alt
LOCAL_SRC_FILES := libomx_framework_alt
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := $(lib_dir)$(LOCAL_MODULE)$(LOCAL_MODULE_SUFFIX)
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(TARGET_OUT)/lib/
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libomx_clock_utils_alt
LOCAL_SRC_FILES := libomx_clock_utils_alt
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := $(lib_dir)$(LOCAL_MODULE)$(LOCAL_MODULE_SUFFIX)
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(TARGET_OUT)/lib/
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libomx_av_core_alt
LOCAL_SRC_FILES := libomx_av_core_alt
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := $(lib_dir)$(LOCAL_MODULE)$(LOCAL_MODULE_SUFFIX)
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(TARGET_OUT)/lib/
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libfpscalculator_alt
LOCAL_SRC_FILES := libfpscalculator_alt
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := $(lib_dir)$(LOCAL_MODULE)$(LOCAL_MODULE_SUFFIX)
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(TARGET_OUT)/lib/
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libdatachunkqueue_alt
LOCAL_SRC_FILES := libdatachunkqueue_alt
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := $(lib_dir)$(LOCAL_MODULE)$(LOCAL_MODULE_SUFFIX)
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(TARGET_OUT)/lib/
include $(BUILD_PREBUILT)

ifeq ($(BOARD_OMX_WITH_TVP),true)
include $(CLEAR_VARS)
LOCAL_MODULE := libsecmem
LOCAL_SRC_FILES := libsecmem
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := $(lib_dir)$(LOCAL_MODULE)$(LOCAL_MODULE_SUFFIX)
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(TARGET_OUT)/vendor/lib/
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := secmem
LOCAL_SRC_FILES := secmem
LOCAL_MODULE_SUFFIX := .tzo
LOCAL_SRC_FILES := $(lib_dir)$(LOCAL_MODULE)$(LOCAL_MODULE_SUFFIX)
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(TARGET_OUT)/lib/
include $(BUILD_PREBUILT)
endif
